### PR TITLE
add DisplaySpecs::COLUMN_OFFSET

### PR DESCRIPTION
**Pull request by agrif**
As discussed in #18, some displays start on a non-zero column address. It looks like this has something to do with `FLIP_COLUMNS` putting columns that used to be off the screen on the high end down into the low addresses.

This PR adds a `COLUMN_OFFSET` parameter added to every `Command::ColumnAddressSet` in graphics mode.

Some notes:
 * I had to add a `SPECS: DisplaySpec<..>` constraint to an impl block. You can't get a graphics mode interface without that constraint, but it is technically an API break for anyone doing something naughty with transmute.
 * Every display spec needs a new `COLUMN_OFFSET` const, which is also an API break. I considered making this default to 0, but no other field has defaults.
 * I have not modified the spec for `DOGL128_6_EXT12V` except to add a 0 offset. This should probably be 4, but I don't have the display and can't test it. (cc: @deltronix)
 * Despite my best efforts, I can't get the tests to run. But the examples compile, and it fixes the particular display I was working on.

### CODE REVIEW

**Comment by Finomnis** [comment]
- The failed test is not your mistake, it seems that the new clippy version added this check. It's quite a while since the last commit to this crate.
- `This should probably be 4` - reason?
- `I can't get the tests to run` - Yah, tests are tricky. I can't remember, though, it was quite a while ago. I think tests are meant for my nrf52840 and requires a manual cargo config to run. Or something similar. You can run them on x86, but you need to change a line in `Cargo.toml` (see the github workflow file)
- `I considered making this default to 0` - is it possible to add a default there? If so, I wouldn't object to it.
- `is technically an API break` - Don't worry. I'll release this as a breaking change anyway.

**Comment by agrif** [comment]
`DOGL128_6_EXT12V` was the display added in #18 that started this discussion. It's 128 pixels wide, but the spec currently says 132, because there's 4 pixels off the side of the screen. At least, that's how I understood it.

Associated consts can have defaults. This might be new, I'm not sure. But nothing else in the trait has defaults, and that's fine. I'd only considered it to prevent a breaking change.

After taking another stab at it, tests were failing to compile on x86 because it was trying to test the examples as well. Adding `--lib` to `cargo test` excluded those and the tests work (and pass) now.

**Comment by Finomnis** [comment]
@agrif If you merge the `main` branch into yours, the failing lint should be fixed.

**Comment by Finomnis** [comment]
> It's 128 pixels wide, but the spec currently says 132, because there's 4 pixels off the side of the screen. At least, that's how I understood it.

The question is whether those are at the beginning or the end of the display. I sadly don't have that display either. :/

**Comment by Finomnis** [comment]
According to https://github.com/Finomnis/st7565/pull/18#issuecomment-1685272070, It would indeed be good to reduce it to `128` and do `offset=4`. Would you mind changing that?

**Comment by agrif** [comment]
For my display, at least, whether the extra columns are at the beginning or the end depends on `FLIP_COLUMNS`. It would be nice if changing `FLIP_COLUMNS` simply mirrored the display without also needing to fiddle with the column offset, but I don't have broad experience with displays to know if this is how it always works.

While investigating this issue I read some displays might have off-screen columns on *both* sides.

I'll make the change to the display from #18.

**Comment by Finomnis** [comment]
Looks good to me. Any reasons from your side why we shouldn't merge this right now?

**Review by Finomnis — APPROVED** [review]

**Comment by Finomnis** [comment]
Published as [v0.4.0](https://crates.io/crates/st7565/0.4.0).

**Pull request merged**
