### PR TITLE
Add DisplaySpecs for a GMG12864-06D Ver. 2.2 LCD board.

### PR DESCRIPTION
**Pull request by eparmstrong**
This is the DisplaySpecs that works for a board I got off aliexpress recently.

### CODE REVIEW

**Comment by Finomnis** [comment]
Hey! Thanks for your contribution.

Out of curiousity, would you mind sharing an image? :)

**Comment by eparmstrong** [comment]
The bias value came from the spec sheet at
https://www.aliexpress.us/item/3256801435469643.html
Most of the other values came from a driver in the u8g2 project.  The
electronic volume was set by experimenting, and
is a value that works well for both with and without the backlight.

**Comment by Finomnis** [comment]
> The bias value came from the spec sheet at https://www.aliexpress.us/item/3256801435469643.html Most of the other values came from a driver in the u8g2 project. The electronic volume was set by experimenting, and is a value that works well for both with and without the backlight.

Sounds sane :)

**Comment by Finomnis** [comment]
I'd still be interested in an image, though, if you don't mind :) I think you are the first person using this crate that isn't me.

**Comment by eparmstrong** [comment]
In case the pictures didn't come through: https://drive.google.com/drive/folders/1ljvQnZjKfYtNQpg-2t4TmhAYYF3GK3Sm

**Comment by Finomnis** [comment]
Cool :)
Released as `v0.1.5`.

Why inverted, btw? I think this display is meant to be used with a black background and white text, as it is less energy consuming.

**Comment by Finomnis** [comment]
@eparmstrong So I'd almost argue that we should set `inverted` to `false` in your display config

**Comment by Finomnis** [comment]
Yah, if you look at [other usages of it](https://www.youtube.com/watch?v=wJvYdFQHkOk), the background is supposed to be the same color as the dead space around the display. Your dead space is black, and your background is also black, meaning your display is not meant to be driven with a white background. It works, of course, but it leaves a weird black border.

Would you be OK with removing the `inverted` flag then? You could still render it like that, of course, but you whould then have to actively render the background with `BinaryColor::On` and the foreground with `BinaryColor::Off`.

Or do you have objections?

**Comment by eparmstrong** [comment]
I think inverted was basically random. I was planning on leaving it as
false but copied the wrong version. That and the orientation are really
user preferences. I picked the orientation so it matched the photo on
AliExpress.

Feel free to change inverted.

I do worry about the boost voltage settings, but it's set to the lowest
value and it's been running all night without a problem.

**Comment by Finomnis** [comment]
In the end, the presets are just guidelines anyway, if someone wants a different setting it's easy to copy-paste them and adjust them, so I think the orientation is fine :)

**Comment by Finomnis** [comment]
I don't know about the boost voltage settings ... As it seems to be a chinese clone thing, I also didn't find a proper datasheet/programming guideline anywhere. But if those are the settings that you copied from U8g2, then it should be fine, I guess :) Feel free to open another PR if it blows up or anything :D

If it draws an expected amount of current and reacts as expected, it can't be completely wrong.

Either way, if you find out something new feel free to open a new PR to correct it :)

**Comment by eparmstrong** [comment]
A longer-term question I have, has to do with the U1 chip in the top left
of the board. It's a spi font chip with 6.5k Chinese characters, 4+ ASCII
fonts and a lot of calculator fonts. It should be possible to share the spi
interface and switch between them with the chip select pins.

The problem is that the st7565 driver takes ownership of the spi bus. Would
it be possible to have a into_graphics_mode function that released the spi
interface and who's flush function took a ref to the spi interface.
Something like:

(spi, disp) = st7565.into_graphics_mode_release();
disp.flush(&mut spi);

The disp would keep ownership of the cs and A0 pins.

This is pushing my understanding of Rust's type system.

**Comment by Finomnis** [comment]
Let's open a new issue for this discussion, it's kind of off-topic for this thread :)

**Comment by Finomnis** [comment]
And with that I mean, would be so kind and open a new issue for this discussion? :) I think I have some thoughts and solutions, I just don't think they are on-topic in this thread.

**Comment by eparmstrong** [comment]
I can do that, but it'll be after I have slept.

**Pull request merged**
